version: '3'

services:
  file-browser:
    image: filebrowser/filebrowser
    container_name: file-browser
    user: 0:0
    ports:
      - 50000:80
    volumes:
      - /:/srv
      - /docker/filebrowser/database.db:/database.db
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
