version: '2'

services:
  file-browser:
    image: filebrowser/filebrowser
    container_name: file-browser
    command: --database /var/lib/docker/volumes/filebrowser/_data/database.db
    user: 0:0
    ports:
      - ${PORT}:80
    volumes:
      - /:/srv
      - /var/lib/docker/volumes/filebrowser/_data/database.db:/database.db
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
