version: '2'

services:
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server
    restart: unless-stopped
    ports:
      - ${PORT}:80
    volumes:
      - data:/data/

volumes:
  data:
    name: vaultwarden-data
