version: '2'

services:
  app:
    image: vaultwarden/server
    container_name: vaultwarden
    ports:
      - ${PORT}:80
    volumes:
      - data:/data/
    restart: unless-stopped
  
volumes:
  data:
