version: '2'

services:
  app:
    image: jc21/nginx-proxy-manager:latest
    container_name: proxy
    restart: unless-stopped
    ports:
      - 80:80
      - ${PORT}:81
      - 443:443
    volumes:
      - data:/data
      - letsencrypt:/etc/letsencrypt
        
volumes:
  data:
  letsencrypt:
