version: "2"

services:
    adguardhome:
        image: adguard/adguardhome
        container_name: adguardhome
        ports:
            - 53:53/tcp
            - 53:53/udp
            - 784:784/udp
            - 853:853/tcp
            - 3000:3000/tcp
            - 10000:80/tcp
            - 10443:443/tcp
        volumes:
            - workdir:/opt/adguardhome/work
            - confdir:/opt/adguardhome/conf
        restart: unless-stopped
        networks:
            - network
    
volumes:
    workdir:
        name: adguardhome_workdir
    confdir:
        name: adguardhome_confdir

networks:
  network:
    name: bridge
    external: true
