version: "2"

services:
    adguardhome:
        container_name: adguardhome
        image: adguard/adguardhome
        restart: unless-stopped
        ports:
            - 53:53/tcp
            - 53:53/udp
            - 784:784/udp
            - 853:853/tcp
            - 3000:3000/tcp
            - ${PORT}:80/tcp
        volumes:
            - workdir:/opt/adguardhome/work
            - confdir:/opt/adguardhome/conf

volumes:
    workdir:
        name: adguardhome-workdir
    confdir:
        name: adguardhome-confdir
