version: "2"

services:
  db:
    container_name: wikijs-database
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: ${DB-PWD}
      POSTGRES_USER: wikijs
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data

  wiki:
    container_name: wikijs
    image: ghcr.io/requarks/wiki:2
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: ${DB-PWD}
      DB_NAME: wiki
    restart: unless-stopped
    ports:
      - ${PORT}:3000

volumes:
  db-data:
    name: wikijs-database
