version: '2'

services:
  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:latest
    restart: unless-stopped
    ports:
      - ${PORT}:3001
    volumes:
      - data:/app/data

volumes:
  data:
    name: uptime-kuma-data
