version: "2"

services:
  wg-easy:
    container_name: wg-easy
    image: weejewel/wg-easy
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    environment:
      - WG_HOST=${DNS}
      - PASSWORD=${PWD}
    ports:
      - ${PORT_WG}:51820/udp
      - ${PORT_WEB}:51821/tcp
    volumes:
      - wg:/etc/wireguard

volumes:
  wg:
    name: wg-easy