version: '2'

services:
  bind9:
    container_name: bind9
    image: internetsystemsconsortium/bind9:9.18
    restart: unless-stopped
    environment:
      - BIND9_USER=root
      - TZ=${TZ}
    ports:
      - 53:53/tcp
      - 53:53/udp
    volumes:
      - etc:/etc/bind
      - cache:/var/cache/bind
      - lib:/var/lib/bind
      - log:/var/log

  adguardhome:
      container_name: adguardhome
      image: adguard/adguardhome:latest
      restart: unless-stopped
      ports:
        - 784:784/udp
        - 853:853/tcp
        - 3000:3000/tcp
        - ${PORT_AD}:80/tcp
      volumes:
        - workdir:/opt/adguardhome/work
        - confdir:/opt/adguardhome/conf

volumes:
  etc:
    name: bind9-etc
  cache:
    name: bind9-cache
  lib:
    name: bind9-lib
  log:
    name: bind9-log
  workdir:
    name: adguardhome-workdir
  confdir:
    name: adguardhome-confdir
